version: '3.8'

services:
  db:
    image: postgres:15
    container_name: atividadesbd_postgres
    restart: always
    environment:
      POSTGRES_USER: atividades_user
      POSTGRES_PASSWORD: atividades_senha
      POSTGRES_DB: AtividadesBD
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_atividades
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  pgdata:
